// Generates levels.js: 5 tiers × 30 levels, each verified solvable, rated, and sorted by difficulty. Run: node tools/gen_levels.js
const fs = require('fs');
const E = require('./engine');

/*
 * Difficulty comes from tightness, not board size (see tools/probe.js):
 * one spare bottle and taller tubes force planning; the casual-player fail rate filters out boards
 * that can be won by grabbing obvious moves. Pools are [colors, cap, spare bottles, empty at start].
 */
const TIERS = [
  { id: 'beginner', fail: [0, 0.3], pools: [[3, 4, 2, 2], [4, 4, 2, 2], [5, 4, 2, 2], [6, 4, 2, 2]] },
  { id: 'easy', fail: [0.15, 0.7], pools: [[6, 4, 2, 2], [7, 4, 2, 2], [8, 4, 2, 2], [5, 5, 2, 2], [6, 5, 2, 2]] },
  { id: 'normal', fail: [0.5, 1], pools: [[8, 4, 2, 1], [9, 4, 2, 1], [7, 5, 2, 2], [8, 5, 2, 1], [4, 4, 1, 1], [5, 4, 1, 1]] },
  { id: 'hard', fail: [0.75, 1], pools: [[5, 4, 1, 1], [6, 4, 1, 1], [4, 5, 1, 1], [5, 5, 1, 1], [4, 6, 1, 1], [7, 4, 1, 1]] },
  { id: 'master', fail: [0.9, 1], minPar: 18, pools: [[6, 4, 1, 1], [7, 4, 1, 1], [8, 4, 1, 1], [5, 5, 1, 1], [6, 5, 1, 1], [5, 6, 1, 1]] },
];
const PER_TIER = 30;
const rand = E.rng(20260930);
const seen = new Set();

const out = TIERS.map(T => {
  const levels = [];
  const quota = T.pools.map((_, i) => Math.floor(PER_TIER / T.pools.length) + (i < PER_TIER % T.pools.length));
  for (let n = 0; levels.length < PER_TIER; n++) {
    const pi = n % T.pools.length;
    if (!quota[pi]) continue;
    const [colors, cap, spare, empty] = T.pools[pi];
    const st = E.deal(colors, cap, spare, empty, rand);
    if (!st || seen.has(st.join('|')) || E.solvable(st, cap) !== true) continue;
    const fail = E.casualFailRate(st, cap, rand);
    if (fail < T.fail[0] || fail > T.fail[1]) continue;
    const sol = E.beamSolve(st, cap);
    if (!sol || sol.length < (T.minPar || 0)) continue;
    seen.add(st.join('|'));
    quota[pi]--;
    levels.push({ cap, par: sol.length, b: st, score: fail * 30 + sol.length + colors * cap / 4 });
  }
  levels.sort((a, b) => a.score - b.score);
  console.log(T.id.padEnd(9), levels.map(l => `${l.b.length}b×${l.cap}/${l.par}`).join(' '));
  return { id: T.id, levels: levels.map(({ cap, par, b }) => ({ cap, par, b })) };
});

fs.writeFileSync(__dirname + '/../levels.js',
  '// Generated by tools/gen_levels.js — every level verified solvable; par = shortest solution found. Layers are chars a..l, bottom→top.\n' +
  'const TIERS = ' + JSON.stringify(out) + ';\n');
